[package]
name = "api_ssn"
version = "0.1.0"
authors = ["romain <romain.lannes@gmail.com>"]

[dependencies]
petgraph = "*"
fnv = "*"
rand = "0.3.0"
easy_cartesians = { path="/home/romain/easy_cartesians"}
